import {Montserrat } from 'next/font/google'
// import {notFound} from 'next/navigation';
import './globals.css'
import "swiper/swiper.min.css";
// import "swiper/components/pagination/pagination.min.css";
const locales = ['en', 'ru', 'uz'];
export const metadata = {
  title: 'Better-future',
  description: 'Generated by create next app',
}
const mont = Montserrat({
  weight: '400',
  subsets:  ['latin', 'latin-ext'],
  variable: '--font-mont',
});

export default function RootLayout({ children, params: {locale} }) {
  if (!locales.includes(locale)) <div>notFound</div>
  return (
    <html lang={locale}>
      <body className={mont.variable}>{children}</body>
    </html>
  )
}
