import { Inter } from 'next/font/google'
import './globals.css'
import 'swiper/css';
import { languages } from '../i18n/settings';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}


export default function RootLayout({children,params: {lng}}) {
  return (
    <html lang={lng}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
